timezone: Madrid/Spain
encoding: utf-8
collections:
 - docs
url: http://guillermobox.github.io
name: guillermobox @ github
author:
 name: Guillermo Indalecio
 email: guillermobox@gmail.com
 gravatar: fde8fdc7df4bafbc91d4fad5ad9363d0
 github: guillermobox
 bitbucket: guillermobox
 googleplus: GuillermoIndalecioFern√°ndez
 occupation: Physicist, developer
 location: Santiago de Compostela, Spain

